networks:
  default:
    name: dpdzero

services:
  go-container:
    build:
      context: ./service1
    container_name: go-container
    expose: 
      - "8001"
    healthcheck:
      test: ["CMD", "wget","-qO-", "http://localhost:8001/ping"]
      interval: 10s
      timeout: 5s
      retries: 3

  python-container:
    build:
      context:  ./service2
    container_name: python-container
    expose:
      - "8002"
    healthcheck:
      test: ["CMD", "wget","-qO-","http://127.0.0.0:8002/ping"]
      interval: 10s
      timeout: 5s
      retries: 3

  nginx:
    build:  
      context:  ./nginx
    container_name: nginx
    ports:
      - "8080:80"

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.47.2
    container_name: cadvisor
    ports:
      - "8081:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    privileged: true
  



    

        

        